server.port=${SUT_PORT:8080}
management.endpoints.web.exposure.include=health,mappings
management.endpoint.health.show-details=never
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
