<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.63.0" />
    <PackageReference Include="Grpc.Tools" Version="2.63.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos/order_api/product.proto" GrpcServices="Server" ProtoRoot="Protos" />
    <Protobuf Include="Protos/order_api/order.proto" GrpcServices="Server" ProtoRoot="Protos" />
    <Protobuf Include="Protos/order_api/product_types.proto" GrpcServices="None" ProtoRoot="Protos" />
    <Protobuf Include="Protos/order_api/order_types.proto" GrpcServices="None" ProtoRoot="Protos" />
    <Protobuf Include="Protos/buf/validate/validate.proto" GrpcServices="None" ProtoRoot="Protos" />
  </ItemGroup>
</Project>
