name: Samples CI

on:
  push:
  pull_request:

jobs:
  no-samples:
    name: No samples configured
    runs-on: ubuntu-latest
    steps:
      - name: Skip sample CI
        run: echo "No samples are currently configured for CI."
